[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]
gas_reports_ignore = ["test/**/*"]

[profile.ci]
fuzz = { runs = 10000 }
verbosity = 4

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 100
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
mainnet = "https://eth-mainnet.alchemyapi.io/v2/YOUR_API_KEY"
goerli = "https://eth-goerli.alchemyapi.io/v2/YOUR_API_KEY"